#task3 profile part
AlexYudenkov/PetCare pull request #4
Opened 2021-09-01 07:24 UTC by MichailSamoylov

2021-09-01 14:20 UTC, merged

2021-09-01 14:25 UTC, AlexYudenkov requested changes
Исправь все недочеты плиз, укажи к каждому, что исправил)

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/extTransition/EnumIdTransition.kt
> +    ADDALARMtoPROFILE(3),
Нейминг просто жуть, надо называть PROFILE_TO_SETTINGS

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/res/drawable/ic_tutrle_icon_group.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
В названии очепятка

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/res/values/colors.xml
> +	<color name="black_40">#66000000</color>
За это лайк)

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +
Зачем тут лишние строки?

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +        listClockData = ItemList.value!!
Вот это не нравится(

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +    init{
Давай лучше сделаем фукнцию типо fetchInformation(), в которой будут находится, что было в init. Во фрагменте сделаем override  onViewCreated() там уже и будем вызывать fetchinformation.

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +    var LogIsClose = true
Давай названия переменных с маленькой буквы, чтобы путаницы не было)

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        private fun openLogClock(sharedPreferences: SharedPreferences, profileViewModel:ProfileViewModel){
Зачем фукнции в companion object?

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +            var editor: SharedPreferences.Editor = sharedPreferences.edit()
val

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.openLogClock(sharedPreferences, profileViewModel)
Вообще не используется

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.openLogClock(sharedPreferences, profileViewModel)
Зачем добавлять, что это фрагмент, если ты и так в нем?

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.saveLogClock(sharedPreferences, profileViewModel)
Тут тоже вопрос вопросов, зачем добавлять что это фрагмент?

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +    fun OpenProfile(imageId: Int, namePet: String, kindPet: String) {
Это, я думаю, не вся же инфа, которую ты решил добавить, имхо, надо бы еще в файлик вынести, чтобы тут не было столько кода

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/MainPageFragment/MainPageFragment.kt
>              contentDescription = "-",
Го будем добавлять по приколу, а то вдруг решим куда-нибудь выложить))

2021-09-01 14:25 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/addAlarmClockPage/AddAlarmClock.kt
> +
тоже лишние строки)

2021-09-01 15:49 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.openLogClock(sharedPreferences, profileViewModel)
не, это просто вызов статик метода для сохранения данных

2021-09-01 15:50 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.saveLogClock(sharedPreferences, profileViewModel)
это не фрагмент, это статик метод

2021-09-01 15:51 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +    fun OpenProfile(imageId: Int, namePet: String, kindPet: String) {
вот тут не понял

2021-09-01 17:23 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/MainPageFragment/MainPageFragment.kt
>              contentDescription = "-",
Ты про про описание контента?

2021-09-02 03:35 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.openLogClock(sharedPreferences, profileViewModel)
А зачем писать, что это ProfilePageFragment ты же и так в нем находишься

2021-09-02 03:36 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/MainPageFragment/MainPageFragment.kt
>              contentDescription = "-",
Да

2021-09-02 03:37 UTC, AlexYudenkov commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +    fun OpenProfile(imageId: Int, namePet: String, kindPet: String) {
Много очень кода, нужно вынести его

2021-09-08 11:45 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/extTransition/EnumIdTransition.kt
> +    ADDALARMtoPROFILE(3),
+

2021-09-08 11:45 UTC, Tedy-hub commented on app/src/main/res/drawable/ic_tutrle_icon_group.xml
>  <vector xmlns:android="http://schemas.android.com/apk/res/android"
+

2021-09-08 11:46 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +
+

2021-09-08 11:46 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +        listClockData = ItemList.value!!
+

2021-09-08 11:47 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfileViewModel.kt
> +    var LogIsClose = true
+

2021-09-08 11:48 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        private fun openLogClock(sharedPreferences: SharedPreferences, profileViewModel:ProfileViewModel){
+

2021-09-08 11:48 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +            var editor: SharedPreferences.Editor = sharedPreferences.edit()
+

2021-09-08 11:48 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.openLogClock(sharedPreferences, profileViewModel)
+

2021-09-08 11:48 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +        ProfilePageFragment.saveLogClock(sharedPreferences, profileViewModel)
+

2021-09-08 11:51 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/ProfilePageFragment.kt
> +    fun OpenProfile(imageId: Int, namePet: String, kindPet: String) {
+

2021-09-08 11:52 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/MainPageFragment/MainPageFragment.kt
>              contentDescription = "-",
+

2021-09-08 11:53 UTC, Tedy-hub commented on app/src/main/java/ru/alexmichael/petcare/ProfilePageFragment/addAlarmClockPage/AddAlarmClock.kt
> +
+